name: Pull Request Logger
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        ORG_ID_GITHUB: ${{ secrets.ORG_ID_GITHUB }}
        TEAM_NAME_GITHUB: ${{ secrets.TEAM_NAME_GITHUB }}
    - run: npm install
    - run: PERSONAL_ACCESS_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} ORG_ID_GITHUB=${{ secrets.ORG_ID_GITHUB }} TEAM_NAME_GITHUB=${{ secrets.TEAM_NAME_GITHUB }} node .github/workflows/pull-request-logger.js
